allowBuilds:
  core-js: true
  esbuild: true
  vue-demi: true
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@txnlab/use-wallet@5.0.0"
  - "@txnlab/use-wallet-defly@5.0.0"
  - "@txnlab/use-wallet-lute@5.0.0"
  - "@txnlab/use-wallet-pera@5.0.0"
  - "@txnlab/use-wallet-vue@5.0.0"
overrides:
  "ws": ">=7.5.10"
  "bn.js": ">=4.12.3"
