allowBuilds:
  core-js: true
  esbuild: true
  vue-demi: true
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@galaxypay/use-wallet-lute@1.0.0'
overrides:
  "ws": ">=7.5.10"
  "bn.js": ">=4.12.3"
