/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlgoIcon: typeof import('./components/svg/AlgoIcon.vue')['default']
    AppBar: typeof import('./components/AppBar.vue')['default']
    AppCard: typeof import('./components/AppCard.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AssetCard: typeof import('./components/AssetCard.vue')['default']
    CustomNode: typeof import('./components/CustomNode.vue')['default']
    DonateDialog: typeof import('./components/DonateDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Snackbar: typeof import('./components/Snackbar.vue')['default']
    VanityMnemonic: typeof import('./components/VanityMnemonic.vue')['default']
    VanitySell: typeof import('./components/VanitySell.vue')['default']
  }
}
