/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/arc200': RouteRecordInfo<'/arc200', '/arc200', Record<never, never>, Record<never, never>>,
    '/badge': RouteRecordInfo<'/badge', '/badge', Record<never, never>, Record<never, never>>,
    '/burn': RouteRecordInfo<'/burn', '/burn', Record<never, never>, Record<never, never>>,
    '/inbox': RouteRecordInfo<'/inbox', '/inbox', Record<never, never>, Record<never, never>>,
    '/keyreg': RouteRecordInfo<'/keyreg', '/keyreg', Record<never, never>, Record<never, never>>,
    '/optout': RouteRecordInfo<'/optout', '/optout', Record<never, never>, Record<never, never>>,
    '/vanity': RouteRecordInfo<'/vanity', '/vanity', Record<never, never>, Record<never, never>>,
  }
}
